In [1]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [8]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [12]:
a1=np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [14]:
a2=np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [15]:
a2.ndim

2

In [16]:
a2.dtype

dtype('int64')

In [17]:
a2.size

6

# Creating Numpy Arrays from Scratch

## zeros,ones,full,arrange,linspace


In [18]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [24]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [25]:
np.random.random((4,4))

array([[0.68201849, 0.79633067, 0.81234342, 0.24404134],
       [0.08645134, 0.25461672, 0.2396649 , 0.45361294],
       [0.86758091, 0.62318922, 0.10627246, 0.63553062],
       [0.12904892, 0.98835899, 0.83630199, 0.98807099]])

In [26]:
np.random.normal(0,1,(3,3))

array([[-0.50069746, -0.27063071,  2.75739058],
       [ 0.70859184, -0.44669497, -1.64548566],
       [-0.06981179, -2.16771047,  0.10357279]])

In [27]:
np.random.randint(0,10,(4,5))

array([[4, 3, 8, 7, 1],
       [6, 3, 0, 4, 8],
       [3, 3, 8, 4, 6],
       [6, 7, 8, 3, 1]])

# Array Indexing & Slicing

## One-dimensional subarray

In [30]:
x1=np.random.randint(20,size=6)
x1

array([17,  6,  0, 18, 16,  7])

In [31]:
x1[4]

16

## Multi-dimensional array

In [32]:
x2=np.random.randint(10,size=(3,4))
x2

array([[6, 1, 1, 7],
       [0, 3, 3, 2],
       [6, 6, 4, 6]])

In [33]:
x2[1,2]=6
x2

array([[6, 1, 1, 7],
       [0, 3, 6, 2],
       [6, 6, 4, 6]])

## Slicing

In [34]:
x1

array([17,  6,  0, 18, 16,  7])

In [35]:
x1[0:3]

array([17,  6,  0])

In [36]:
x1[2:4]

array([ 0, 18])

In [37]:
x1[::2]

array([17,  0, 16])

In [38]:
x2

array([[6, 1, 1, 7],
       [0, 3, 6, 2],
       [6, 6, 4, 6]])

In [39]:
x2[:2,:3]

array([[6, 1, 1],
       [0, 3, 6]])

In [40]:
x2[:,:2]

array([[6, 1],
       [0, 3],
       [6, 6]])

## Reshaping of Arrays & Transpose

In [41]:
grid=np.arange(1,10)
grid.shape

(9,)

In [42]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x=np.array([1,2,3])
x.shape

(3,)

In [45]:
x=np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [46]:
x.T

array([[1., 3.],
       [2., 4.]])

## Array Concatenation and Splitting

In [48]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [49]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [50]:
grid=np.array([[1,2,3],[4,5,6]])

In [51]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])