In [1]:
import numpy as np

# Creating Numpy Arrays from Python Lists

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [8]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [12]:
a1=np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [14]:
a2=np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [15]:
a2.ndim

2

In [16]:
a2.dtype

dtype('int64')

In [17]:
a2.size

6

# Creating Numpy Arrays from Scratch

## zeros,ones,full,arrange,linspace


In [18]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [24]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [25]:
np.random.random((4,4))

array([[0.68201849, 0.79633067, 0.81234342, 0.24404134],
       [0.08645134, 0.25461672, 0.2396649 , 0.45361294],
       [0.86758091, 0.62318922, 0.10627246, 0.63553062],
       [0.12904892, 0.98835899, 0.83630199, 0.98807099]])

In [26]:
np.random.normal(0,1,(3,3))

array([[-0.50069746, -0.27063071,  2.75739058],
       [ 0.70859184, -0.44669497, -1.64548566],
       [-0.06981179, -2.16771047,  0.10357279]])

In [27]:
np.random.randint(0,10,(4,5))

array([[4, 3, 8, 7, 1],
       [6, 3, 0, 4, 8],
       [3, 3, 8, 4, 6],
       [6, 7, 8, 3, 1]])

# Array Indexing & Slicing

## One-dimensional subarray

In [30]:
x1=np.random.randint(20,size=6)
x1

array([17,  6,  0, 18, 16,  7])

In [31]:
x1[4]

16

## Multi-dimensional array

In [32]:
x2=np.random.randint(10,size=(3,4))
x2

array([[6, 1, 1, 7],
       [0, 3, 3, 2],
       [6, 6, 4, 6]])

In [33]:
x2[1,2]=6
x2

array([[6, 1, 1, 7],
       [0, 3, 6, 2],
       [6, 6, 4, 6]])

## Slicing

In [34]:
x1

array([17,  6,  0, 18, 16,  7])

In [35]:
x1[0:3]

array([17,  6,  0])

In [36]:
x1[2:4]

array([ 0, 18])

In [37]:
x1[::2]

array([17,  0, 16])

In [38]:
x2

array([[6, 1, 1, 7],
       [0, 3, 6, 2],
       [6, 6, 4, 6]])

In [39]:
x2[:2,:3]

array([[6, 1, 1],
       [0, 3, 6]])

In [40]:
x2[:,:2]

array([[6, 1],
       [0, 3],
       [6, 6]])

## Reshaping of Arrays & Transpose

In [41]:
grid=np.arange(1,10)
grid.shape

(9,)

In [42]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
x=np.array([1,2,3])
x.shape

(3,)

In [45]:
x=np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [46]:
x.T

array([[1., 3.],
       [2., 4.]])

## Array Concatenation and Splitting

In [48]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [49]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [50]:
grid=np.array([[1,2,3],[4,5,6]])

In [51]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [57]:
#stack
x=np.array([1,2,3])
grid=np.array([[9,8,7],[4,5,6]])

np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [59]:
# horizontally stack the arrays: hstack
y=np.array([[99],[9]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [ 9,  4,  5,  6]])

## Splitting on arrays

In [60]:
x=np.array([1,2,3,99,69,3,2,1])

In [63]:
x1,x2,x3=np.split(x,[3,5])

In [64]:
x1

array([1, 2, 3])

In [65]:
x2

array([99, 69])

In [66]:
x3

array([3, 2, 1])

# Broadcasting and Vectorized operations

In [71]:
a=np.arange(3)
a

array([0, 1, 2])

In [72]:
a+5

array([5, 6, 7])

In [74]:
b=np.ones((3,3))

In [75]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a.shape,b.shape

((3,), (3, 3))

In [77]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [78]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [79]:
c=np.arange(3).reshape((3,1))

In [80]:
c

array([[0],
       [1],
       [2]])

In [81]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays

In [82]:
list_number=[1,2,3]

In [83]:
ll=np.array(list_number)

In [84]:
ll

array([1, 2, 3])

In [85]:
sum(ll)

6

In [86]:
np.sum(ll)

6

In [87]:
# Creat a massive Numpy array

massive_array=np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [89]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

375 µs ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.11 µs ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [90]:
np.mean(massive_array)

0.49922144804514534

In [91]:
np.max(massive_array)

0.99985171562227

In [92]:
np.min(massive_array)

0.00012023052593568284

In [94]:
dog_height=[600,470,170,430,300]
dog_height=np.array(dog_height)

np.std(dog_height)

147.32277488562318

In [95]:
np.var(dog_height)

21704.0

In [96]:
np.sqrt(np.var(dog_height))

147.32277488562318

# Sorting Arrays

In [98]:
x=np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [99]:
np.argsort(x)

array([1, 0, 3, 2, 4])

## Sorting along rows or columns

In [101]:
np.random.seed(42)

MatA=np.random.randint(0,10,size=(4,6))

In [102]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [104]:
np.sort(MatA,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

## Linear Algebra

In [105]:
A=np.array(([[1,2,3],[4,5,6],[7,8,9]]))

In [106]:
B=np.array([[6,5],[4,3],[2,1]])

In [107]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [108]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [109]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Dot Product Example

In [110]:
#number of jars sold
np.random.seed(0)

sales_amounts =np.random.randint(20,size=(5,3))

In [111]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [112]:
#Create weekly_sales Dataframe
import pandas as pd

weekly_sales =pd.DataFrame(sales_amounts,index=["Mon",'Tues',"Wed","Thurs","Fri"],
                                         columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [118]:
# creat a price array

prices =np.array([10,8,12])

In [119]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [120]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [121]:
total_prices=weekly_sales.dot(butter_prices.T)

In [122]:
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142